from pathlib import Path
import json
from PIL import Image
import os
import string

target_dir = Path(".")
subdirs = [x for x in target_dir.iterdir() if x.is_dir()]
os.makedirs("./output", exist_ok=True)
output_dir = Path("./output")
for item in output_dir.iterdir():
    if not item.is_dir():
        item.unlink()

bytes_per_px = {
    "ia8": 1,
    "rgba5551": 2,
}

def getBoundingBox(img):
    alpha = img.getchannel("A")
    bounding = alpha.getbbox()

    if bounding:
        height = bounding[3]
        return height
    return 0

BBOX_IMMUNE = string.ascii_uppercase + string.digits

with open("../src/font.c", "w") as fh:
    with open("../include/font.h", "w") as fg:
        fg.write("// This file is autogenerated. See /font/joiner.py for the conversion file\n")
        fh.write("// This file is autogenerated. See /font/joiner.py for the conversion file\n")
        fh.write("#include \"modding.h\"\n")
        fh.write("#include \"ultra64.h\"\n")
        fh.write("#include \"enums.h\"\n")
        fh.write("#include \"common_structs.h\"\n")
        fh.write("#include \"font.h\"\n")
        fg.write("typedef struct CharStruct {\n")
        fg.write("\tu16 x_start;\n")
        fg.write("\tu8 width;\n")
        fg.write("} CharStruct;\n")
        for subdir in subdirs:
            if subdir.name == "output":
                continue
            config = None
            with open(f"{subdir.name}/config.json", "r", encoding="utf-8") as f:
                config = json.load(f)
            height = config["height"]
            width = int((4096 / config["height"]) / bytes_per_px[config["format"]])
            dec = width % 8
            if dec != 0 and dec != 8:
                width -= dec
            print(f"Font {config['font_index']} width: {width}")
            config_data = []
            images = [Image.new("RGBA", (width, height), (0, 0, 0, 0))]
            x_position = 0
            char_string = []
            position_data = []
            bbox_delta = []
            starting_characters = [0]
            letter_counter = 0
            fh.write(f"CharStruct font_{config['font_index']}_characters[] = " + "{\n")
            for filename, letter in config["char_mapping"].items():
                lt = Image.open(f"{subdir.name}/{filename}.png")
                if config['font_index'] == 6:
                    delta = getBoundingBox(lt)
                    if delta > 12 and letter not in BBOX_IMMUNE:
                        bbox_delta.append(12 - delta)
                    else:
                        bbox_delta.append(0)
                elif config['font_index'] == 1:
                    bbox_delta.append(0)
                w, h = lt.size
                if h > height:
                    raise Exception(f"Image {filename} has a height that's too big")
                if (x_position + w) > width:
                    images.append(Image.new("RGBA", (width, height), (0, 0, 0, 0)))
                    x_position = 0
                    starting_characters.append(letter_counter)
                if lt.mode != "RGBA":
                    lt = lt.convert("RGBA")
                images[-1].alpha_composite(lt, dest=(x_position, 0))
                fh.write("{ " + str(x_position) + ", " + str(w) + "},\n")
                position_data.append({
                    "x_start": x_position,
                    "width": w,
                    "char": letter,
                    "file": len(images) - 1
                })
                char_string.append(letter.encode("latin-1")[0])
                x_position += (w + 1)
                letter_counter += 1
            starting_characters.append(letter_counter)
            fh.write("};\n")
            with open(f"output/{subdir.name}_positioning.json", "w") as jsonf:
                json.dump(position_data, jsonf, indent=4)
            sizes = []
            for index, img in enumerate(images):
                img.save(f"output/{subdir.name}_{index}.png")
                px = img.load()
                w, h = img.size
                px_data = []
                fmt = config["format"]
                for y in range(h):
                    for x in range(w):
                        r, g, b, a = px[x, y]
                        if fmt == "ia8":
                            intensity = (r >> 4) & 0xF
                            alpha = (a >> 4) & 0xF
                            px_data.append((intensity << 4) | alpha)
                        elif fmt == "rgba5551":
                            r0 = (r >> 3) & 0x1F
                            g0 = (g >> 3) & 0x1F
                            b0 = (b >> 3) & 0x1F
                            a0 = 1 if a > 128 else 0
                            color = (r0 << 11) | (g0 << 6) | (b0 << 1) | a0
                            px_data.append((color >> 8) & 0xFF)
                            px_data.append(color & 0xFF)
                fh.write(f"u8 font_{config['font_index']}_file{index}[] = " + "{")
                for p in px_data:
                    fh.write(f"{p}, ")
                fh.write("};\n")
                sizes.append(len(px_data))
            fh.write(f"u8 fontstring_{config['font_index']}[] = " + "{")
            for c in char_string:
                fh.write(f"{c}, ")
            fh.write("};\n")
            fh.write(f"u16 fontsizes_{config['font_index']}[] = " + "{")
            for s in sizes:
                fh.write(f"{s}, ")
            fh.write("};\n")
            fh.write(f"u8 *fonttextures_{config['font_index']}[] = " + "{\n")
            for idx in range(len(images)):
                fh.write(f"\t&font_{config['font_index']}_file{idx}[0], \n")
            fh.write("};\n")
            fh.write(f"u8 fontstarts_{config['font_index']}[] = " + "{")
            for stchr in starting_characters:
                fh.write(f"{stchr}, ")
            fh.write("};\n")
            fh.write(f"s8 fontydeltas_{config['font_index']}[] = " + "{")
            for fdelta in bbox_delta:
                fh.write(f"{fdelta}, ")
            fh.write("};\n")
            fg.write(f"#define FONT_{config['font_index']}_COUNT {len(images)}\n")